stages:
  pull_data:
    cmd: python src/pull_data.py data/db_pull_calibrated.parquet data/db_pull_uncalibrated.parquet
    deps:
    - src/pull_data.py
    - src/utils/dbconnector.py
    params:
    - database.questdb
    outs:
    - data/db_pull_calibrated.parquet
    - data/db_pull_uncalibrated.parquet
  resample:
    cmd: python src/resample.py data/db_pull_calibrated.parquet 50 linear
    deps:
    - data/db_pull_calibrated.parquet
    - src/resample.py
    outs:
    - data/resample.parquet
  segmentate:
    cmd: python src/segmentate.py data/resample.parquet 5 0
    deps:
    - data/resample.parquet
    - src/segmentate.py
    outs:
    - data/segmentate.dill
  moving_average:
    cmd: python src/moving_average.py data/resample.parquet data/moving_average.parquet
    deps:
    - data/resample.parquet
    - src/moving_average.py
    params:
    - moving_average.window_len_s
    outs:
    - data/moving_average.parquet
  pca:
    cmd: python src/pca.py data/resample.parquet 6
    deps:
    - data/resample.parquet
    - src/pca.py
    outs:
    - data/pca.parquet
  train_test_split:
    cmd: python src/train_test_split.py data/segmentate.dill data/train_test_split.json
    deps:
    - src/train_test_split.py
    - data/segmentate.dill
    params:
    - train_test_split
    outs:
    - data/train_test_split.json
  correlations:
    cmd: python src/correlations.py data/segmentate.dill data/correlations.parquet pearson
    deps:
    - src/correlations.py
    - data/segmentate.dill
    outs:
    - data/correlations.parquet
  mlp:
    cmd: python src/model_runner.py data/correlations.parquet data/train_test_split.json MLP Tabular 72 6 --num_epochs 5
    deps:
    - src/model_runner.py
    - src/models/MLP.py
    - src/models/__IModel.py
    - src/models/utils/DataLoaderTabular.py
    - src/models/utils/DataSetTabular.py
    - data/correlations.parquet
    - data/train_test_split.json
    params:
    - OneHotEncode
