stages:
  pull_data_1:
    cmd: python src/pull_data.py pull_data_1 data/db_pull_1.parquet
    deps:
    - src/pull_data.py
    - src/utils/dbconnector.py
    params:
    - pull_data_1
    outs:
    - data/db_pull_1.parquet

  resample_1:
    cmd: python src/resample.py resample_1 data/db_pull_1.parquet data/resample_1.parquet
    deps:
    - data/db_pull_1.parquet
    - src/resample.py
    params:
    - resample_1
    outs:
    - data/resample_1.parquet

  segmentate_1:
    cmd: python src/segmentate.py segmentate_1 data/resample_1.parquet data/segmentate_1.dill
    deps:
    - data/resample_1.parquet
    - src/segmentate.py
    params:
    - segmentate_1
    outs:
    - data/segmentate_1.dill

  std-scale_1:
    cmd: python src/standard-scaler.py std-scale_1 data/db_pull_1.parquet data/standard-scaled_1.parquet data/standard-scaler-means_1.csv data/standard-scaler-stds_1.csv
    deps:
    - data/db_pull_1.parquet
    - src/standard-scaler.py
    outs:
    - data/standard-scaled_1.parquet
    - data/standard-scaler-means_1.csv
    - data/standard-scaler-stds_1.csv

  min-max-scale_1:
    cmd: python src/min-max-scaler.py min-max-scale_1 data/db_pull_1.parquet data/min-max-scaled_1.parquet data/min-max-scaler-maxs_1.csv data/min-max-scaler-mins_1.csv
    deps:
    - data/db_pull_1.parquet
    - src/min-max-scaler.py
    params:
    - min-max-scale_1
    outs:
    - data/min-max-scaled_1.parquet
    - data/min-max-scaler-maxs_1.csv
    - data/min-max-scaler-mins_1.csv

  fft_1:
    cmd: python src/fft.py fft_1 data/segmentate_1.dill data/fft_1.dill
    deps:
    - data/segmentate_1.dill
    - src/fft.py
    outs:
    - data/fft_1.dill

  filter_bandpass_1:
    cmd: python src/butterworth_filter.py filter_bandpass_1 data/segmentate_1.dill data/bandpass_1.dill
    deps:
    - data/segmentate_1.dill
    - src/butterworth_filter.py
    - src/utils/filters.py
    params:
    - filter_bandpass_1
    outs:
    - data/bandpass_1.dill

  filter_lowpass_1:
    cmd: python src/butterworth_filter.py filter_lowpass_1 data/segmentate_1.dill data/lowpass_1.dill
    deps:
    - data/segmentate_1.dill
    - src/butterworth_filter.py
    - src/utils/filters.py
    params:
    - filter_lowpass_1
    outs:
    - data/lowpass_1.dill

  filter_highpass_1:
    cmd: python src/butterworth_filter.py filter_highpass_1 data/segmentate_1.dill data/highpass_1.dill
    deps:
    - data/segmentate_1.dill
    - src/butterworth_filter.py
    - src/utils/filters.py
    params:
    - filter_highpass_1
    outs:
    - data/highpass_1.dill

  moving_average_1:
    cmd: python src/moving_average.py moving_average_1 data/resample_1.parquet data/moving_average_1.parquet
    deps:
    - data/resample_1.parquet
    - src/moving_average.py
    params:
    - moving_average_1
    outs:
    - data/moving_average_1.parquet

  pca_1:
    cmd: python src/pca.py pca_1 data/resample_1.parquet data/pca_1.parquet
    deps:
    - data/resample_1.parquet
    - src/pca.py
    params:
    - pca_1
    outs:
    - data/pca_1.parquet

  train_test_split_1:
    cmd: python src/train_test_split.py train_test_split_1 data/segmentate_1.dill data/train_test_split_1.json
    deps:
    - data/segmentate_1.dill
    - src/train_test_split.py
    params:
    - train_test_split_1
    outs:
    - data/train_test_split_1.json

  correlations_1:
    cmd: python src/correlations.py correlations_1 data/segmentate_1.dill data/correlations_1.parquet 
    deps:
    - data/segmentate_1.dill
    - src/correlations.py
    params:
    - correlations_1
    outs:
    - data/correlations_1.parquet 

  aggregate_1:
    cmd: python src/aggregate.py aggregate_1 data/segmentate_1.dill data/aggregate_1.dill
    deps:
    - data/segmentate_1.dill
    - src/aggregate.py
    params:
    - aggregate_1
    outs:
    - data/aggregate_1.dill