stages:
  pull_data:
    cmd: python src/pull_data.py data/db_pull_calibrated.parquet data/db_pull_uncalibrated.parquet
    deps:
    - src/pull_data.py
    - src/utils/dbconnector.py
    params:
    - database.questdb
    outs:
    - data/db_pull_calibrated.parquet
    - data/db_pull_uncalibrated.parquet
  resample:
    cmd: python src/resample.py data/db_pull_calibrated.parquet 50 linear
    deps:
    - data/db_pull_calibrated.parquet
    - src/resample.py
    outs:
    - data/resample.parquet
  segmentate:
    cmd: python src/segmentate.py data/resample.parquet 5 0
    deps:
    - data/resample.parquet
    - src/segmentate.py
    outs:
    - data/segmentate.dill
  std-scale:
    cmd: python src/standard-scaler.py data/db_pull_calibrated.parquet
    deps:
    - data/db_pull_calibrated.parquet
    - src/standard-scaler.py
    outs:
    - data/standard-scaled.parquet
    - data/standard-scaler-means.csv
    - data/standard-scaler-stds.csv
  min-max-scale:
    cmd: python src/min-max-scaler.py data/db_pull_calibrated.parquet 0 1
    deps:
    - data/db_pull_calibrated.parquet
    - src/min-max-scaler.py
    outs:
    - data/min-max-scaled.parquet
    - data/min-max-scaler-maxs.csv
    - data/min-max-scaler-mins.csv
  moving_average:
    cmd: python src/moving_average.py data/resample.parquet data/moving_average.parquet
    deps:
    - data/resample.parquet
    - src/moving_average.py
    params:
    - moving_average.window_len_s
    outs:
    - data/moving_average.parquet
  pca:
    cmd: python src/pca.py data/resample.parquet 6
    deps:
    - data/resample.parquet
    - src/pca.py
    outs:
    - data/pca.parquet
  train_test_split:
    cmd: python src/train_test_split.py data/segmentate.dill data/train_test_split.json
    deps:
    - src/train_test_split.py
    - data/segmentate.dill
    params:
    - train_test_split
    outs:
    - data/train_test_split.json
