stages:
  pull_data_calibrated:
    cmd: python src/pull_data.py pull_data_calibrated data/db_pull_calibrated.parquet
    deps:
    - src/pull_data.py
    - src/utils/dbconnector.py
    params:
    - pull_data_calibrated
    outs:
    - data/db_pull_calibrated.parquet

  resample_50Hz:
    cmd: python src/resample.py resample_50Hz data/db_pull_calibrated.parquet data/resample_50Hz.parquet
    deps:
    - data/db_pull_calibrated.parquet
    - src/resample.py
    params:
    - resample_50Hz
    outs:
    - data/resample_50Hz.parquet

  segmentate_5s:
    cmd: python src/segmentate.py segmentate_5s data/resample_50Hz.parquet data/segmentate_5s.dill
    deps:
    - data/resample_50Hz.parquet
    - src/segmentate.py
    params:
    - segmentate_5s
    outs:
    - data/segmentate_5s.dill

  std-scale:
    cmd: python src/standard-scaler.py std-scale data/db_pull_calibrated.parquet data/standard-scaled.parquet data/standard-scaler-means.csv data/standard-scaler-stds.csv
    deps:
    - data/db_pull_calibrated.parquet
    - src/standard-scaler.py
    outs:
    - data/standard-scaled.parquet
    - data/standard-scaler-means.csv
    - data/standard-scaler-stds.csv

  min-max-scale_min0_max1:
    cmd: python src/min-max-scaler.py min-max-scale_min0_max1 data/db_pull_calibrated.parquet data/min-max-scaled_min0_max1.parquet data/min-max-scaler-maxs_min0_max1.csv data/min-max-scaler-mins_min0_max1.csv
    deps:
    - data/db_pull_calibrated.parquet
    - src/min-max-scaler.py
    params:
    - min-max-scale_min0_max1
    outs:
    - data/min-max-scaled_min0_max1.parquet
    - data/min-max-scaler-maxs_min0_max1.csv
    - data/min-max-scaler-mins_min0_max1.csv

  fft:
    cmd: python src/fft.py fft data/segmentate_5s.dill data/fft.dill
    deps:
    - data/segmentate_5s.dill
    - src/fft.py
    outs:
    - data/fft.dill

  filter_bandpass_ord3_low01_high100:
    cmd: python src/butterworth_filter.py filter_bandpass_ord3_low01_high100 data/segmentate_5s.dill data/bandpass_ord3_low01_high100.dill
    deps:
    - data/segmentate_5s.dill
    - src/butterworth_filter.py
    - src/utils/filters.py
    params:
    - filter_bandpass_ord3_low01_high100
    outs:
    - data/bandpass_ord3_low01_high100.dill

  filter_lowpass_ord3_cut100:
    cmd: python src/butterworth_filter.py filter_lowpass_ord3_cut100 data/segmentate_5s.dill data/lowpass_ord3_cut100.dill
    deps:
    - data/segmentate_5s.dill
    - src/butterworth_filter.py
    - src/utils/filters.py
    params:
    - filter_lowpass_ord3_cut100
    outs:
    - data/lowpass_ord3_cut100.dill

  filter_highpass_ord3_cut01:
    cmd: python src/butterworth_filter.py filter_highpass_ord3_cut01 data/segmentate_5s.dill data/highpass_ord3_cut01.dill
    deps:
    - data/segmentate_5s.dill
    - src/butterworth_filter.py
    - src/utils/filters.py
    params:
    - filter_highpass_ord3_cut01
    outs:
    - data/highpass_ord3_cut01.dill

  moving_average_5s:
    cmd: python src/moving_average.py moving_average_5s data/resample_50Hz.parquet data/moving_average_5s.parquet
    deps:
    - data/resample_50Hz.parquet
    - src/moving_average.py
    params:
    - moving_average_5s
    outs:
    - data/moving_average_5s.parquet

  pca_comp6:
    cmd: python src/pca.py pca_comp6 data/resample_50Hz.parquet data/pca_comp6.parquet
    deps:
    - data/resample_50Hz.parquet
    - src/pca.py
    params:
    - pca_comp6
    outs:
    - data/pca_comp6.parquet

  train_test_split_ratio02:
    cmd: python src/train_test_split.py train_test_split_ratio02 data/segmentate_5s.dill data/train_test_split_ratio02.json
    deps:
    - data/segmentate_5s.dill
    - src/train_test_split.py
    params:
    - train_test_split_ratio02
    outs:
    - data/train_test_split_ratio02.json

  correlations_pearson:
    cmd: python src/correlations.py correlations_pearson data/segmentate_5s.dill data/correlations_pearson.parquet 
    deps:
    - data/segmentate_5s.dill
    - src/correlations.py
    params:
    - correlations_pearson
    outs:
    - data/correlations_pearson.parquet 

  aggregate_mean_median_std:
    cmd: python src/aggregate.py aggregate_mean_median_std data/segmentate_5s.dill data/aggregate_mean_median_std.dill
    deps:
    - data/segmentate_5s.dill
    - src/aggregate.py
    params:
    - aggregate_mean_median_std
    outs:
    - data/aggregate_mean_median_std.dill

  dvclive:
    cmd: python src/model_runner.py dvclive data/correlations_pearson.parquet data/train_test_split_ratio02.json data/mlp_model.pt data/mlp_output_test.csv
    deps:
    - src/model_runner.py
    - src/models/MLP.py
    - src/models/__IModel.py
    - src/models/utils/DataLoaderSklearn.py
    - src/models/utils/DataLoaderTabular.py
    - src/models/utils/DataSetTabular.py
    - data/correlations_pearson.parquet
    - data/train_test_split_ratio02.json
    params:
    - dvclive
    outs: # TODO: how do we name model outputs when all are trained using dvclive stage?
    - data/mlp_model.pt 
    - data/mlp_output_test.csv
    metrics:
    - dvclive/metrics.json:
        cache: true
    plots:
    - dvclive/plots:
        cache: true

  evaluate:
    cmd: python src/evaluate.py evaluate data\mlp_output_test.csv data/confusion_matrix.png
    deps:
    - src/evaluate.py
    - data/mlp_output_test.csv
    outs:
    - data/confusion_matrix.png