stages:
  pull_data_calibrated:
    cmd: python src/pull_data.py pull_data_calibrated data/db_pull_calibrated.parquet
    deps:
    - src/pull_data.py
    - src/utils/dbconnector.py
    params:
    - pull_data_calibrated
    outs:
    - data/db_pull_calibrated.parquet

  resample_50Hz:
    cmd: python src/resample.py resample_50Hz data/db_pull_calibrated.parquet data/resample_50Hz.parquet
    deps:
    - data/db_pull_calibrated.parquet
    - src/resample.py
    params:
    - resample_50Hz
    outs:
    - data/resample_50Hz.parquet

  segmentate_5s:
    cmd: python src/segmentate.py segmentate_5s data/resample_50Hz.parquet data/segmentate_5s.dill
    deps:
    - data/resample_50Hz.parquet
    - src/segmentate.py
    params:
    - segmentate_5s
    outs:
    - data/segmentate_5s.dill

  fft:
    cmd: python src/fft.py fft data/segmentate_5s.dill data/fft.dill
    deps:
    - data/segmentate_5s.dill
    - src/fft.py
    outs:
    - data/fft.dill

  stft:
    cmd: python src/stft.py stft data/segmentate_5s.dill data/stft.dill
    deps:
    - data/segmentate_5s.dill
    - src/stft.py
    outs:
    - data/stft.dill

  filter_bandpass_ord3_low01_high100:
    cmd: python src/butterworth_filter.py filter_bandpass_ord3_low01_high100 data/segmentate_5s.dill data/bandpass_ord3_low01_high100.dill
    deps:
    - data/segmentate_5s.dill
    - src/butterworth_filter.py
    - src/utils/filters.py
    params:
    - filter_bandpass_ord3_low01_high100
    outs:
    - data/bandpass_ord3_low01_high100.dill

  filter_lowpass_ord3_cut100:
    cmd: python src/butterworth_filter.py filter_lowpass_ord3_cut100 data/segmentate_5s.dill data/lowpass_ord3_cut100.dill
    deps:
    - data/segmentate_5s.dill
    - src/butterworth_filter.py
    - src/utils/filters.py
    params:
    - filter_lowpass_ord3_cut100
    outs:
    - data/lowpass_ord3_cut100.dill

  filter_highpass_ord3_cut01:
    cmd: python src/butterworth_filter.py filter_highpass_ord3_cut01 data/segmentate_5s.dill data/highpass_ord3_cut01.dill
    deps:
    - data/segmentate_5s.dill
    - src/butterworth_filter.py
    - src/utils/filters.py
    params:
    - filter_highpass_ord3_cut01
    outs:
    - data/highpass_ord3_cut01.dill

  moving_average_01s:
    cmd: python src/moving_average.py moving_average_01s data/segmentate_5s.dill data/moving_average_01s.dill
    deps:
    - data/segmentate_5s.dill
    - src/moving_average.py
    params:
    - moving_average_01s
    outs:
    - data/moving_average_01s.dill

  train_test_split_ratio02:
    cmd: python src/train_test_split.py train_test_split_ratio02 data/segmentate_5s.dill data/train_test_split_ratio02.json
    deps:
    - data/segmentate_5s.dill
    - src/train_test_split.py
    params:
    - train_test_split_ratio02
    outs:
    - data/train_test_split_ratio02.json

  correlations_pearson:
    cmd: python src/correlations.py correlations_pearson data/segmentate_5s.dill data/correlations_pearson.parquet 
    deps:
    - data/segmentate_5s.dill
    - src/correlations.py
    params:
    - correlations_pearson
    outs:
    - data/correlations_pearson.parquet 

  aggregate_mean_median_std:
    cmd: python src/aggregate.py aggregate_mean_median_std data/segmentate_5s.dill data/aggregate_mean_median_std.dill
    deps:
    - data/segmentate_5s.dill
    - src/aggregate.py
    params:
    - aggregate_mean_median_std
    outs:
    - data/aggregate_mean_median_std.dill

  transform_min_max:
    cmd: python src/transform.py transform_min_max data/segmentate_5s.dill data/train_test_split_ratio02.json data/segments_min_max.dill data/transformer_min_max.dill
    deps:
    - data/segmentate_5s.dill
    - data/train_test_split_ratio02.json
    - src/transform.py
    - src/utils/transformers.py
    params:
    - transform_min_max
    outs:
    - data/segments_min_max.dill 
    - data/transformer_min_max.dill

  transform_standardize:
    cmd: python src/transform.py transform_standardize data/segmentate_5s.dill data/train_test_split_ratio02.json data/segments_standardized.dill data/transformer_standardize.dill
    deps:
    - data/segmentate_5s.dill
    - data/train_test_split_ratio02.json
    - src/transform.py
    - src/utils/transformers.py
    params:
    - transform_standardize
    outs:
    - data/segments_standardized.dill 
    - data/transformer_standardize.dill

  transform_pca:
    cmd: python src/transform.py transform_pca data/segmentate_5s.dill data/train_test_split_ratio02.json data/segments_pca.dill data/transformer_pca.dill
    deps:
    - data/segmentate_5s.dill
    - data/train_test_split_ratio02.json
    - src/transform.py
    - src/utils/transformers.py
    params:
    - transform_pca
    outs:
    - data/segments_pca.dill 
    - data/transformer_pca.dill

  dvclive:
    cmd: python src/model_runner.py dvclive data/stft.dill data/train_test_split_ratio02.json data/model.pkl data/output_test.csv
    deps:
    - src/model_runner.py
    - src/models/__IModel.py
    - src/models/CNN.py
    - src/models/utils/DataLoaderNDArray.py
    - src/models/utils/DataSetTabular.py
    - data/stft.dill
    - data/train_test_split_ratio02.json
    params:
    - dvclive
    outs:
    - data/model.pkl
    - data/output_test.csv
    metrics:
    - dvclive/metrics.json:
        cache: true
    plots:
    - dvclive/plots:
        cache: true

  evaluate:
    cmd: python src/evaluate.py evaluate data/output_test.csv evaluation/confusion_matrix.png
    deps:
    - src/evaluate.py
    - data/output_test.csv
    outs:
    - evaluation/confusion_matrix.png

  cross_validation_split:
    cmd: python src/train_test_split.py cross_validation_split data/segmentate_5s.dill data/cross_validation_split
    deps:
    - data/segmentate_5s.dill
    - src/train_test_split.py
    params:
    - cross_validation_split
    outs:
    - data/cross_validation_split_1.json
    - data/cross_validation_split_2.json
    - data/cross_validation_split_3.json
    - data/cross_validation_split_4.json
    - data/cross_validation_split_5.json
    - data/cross_validation_split_6.json
    - data/cross_validation_split_7.json
    - data/cross_validation_split_8.json
    - data/cross_validation_split_9.json
    - data/cross_validation_split_10.json

  cross_validation_run_1:
    cmd: python src/model_runner.py dvclive data/stft.dill data/cross_validation_split_1.json data/model_cv_1.pkl data/output_test_cv_1.csv
    deps:
    - src/model_runner.py
    - src/models/__IModel.py
    - src/models/CNN.py
    - src/models/utils/DataLoaderNDArray.py
    - src/models/utils/DataSetTabular.py
    - data/stft.dill
    - data/cross_validation_split_1.json
    params:
    - dvclive
    outs:
    - data/model_cv_1.pkl
    - data/output_test_cv_1.csv

  cross_validation_run_2:
    cmd: python src/model_runner.py dvclive data/stft.dill data/cross_validation_split_2.json data/model_cv_2.pkl data/output_test_cv_2.csv
    deps:
    - src/model_runner.py
    - src/models/__IModel.py
    - src/models/CNN.py
    - src/models/utils/DataLoaderNDArray.py
    - src/models/utils/DataSetTabular.py
    - data/stft.dill
    - data/cross_validation_split_2.json
    params:
    - dvclive
    outs:
    - data/model_cv_2.pkl
    - data/output_test_cv_2.csv

  cross_validation_run_3:
    cmd: python src/model_runner.py dvclive data/stft.dill data/cross_validation_split_3.json data/model_cv_3.pkl data/output_test_cv_3.csv
    deps:
    - src/model_runner.py
    - src/models/__IModel.py
    - src/models/CNN.py
    - src/models/utils/DataLoaderNDArray.py
    - src/models/utils/DataSetTabular.py
    - data/stft.dill
    - data/cross_validation_split_3.json
    params:
    - dvclive
    outs:
    - data/model_cv_3.pkl
    - data/output_test_cv_3.csv

  cross_validation_run_4:
    cmd: python src/model_runner.py dvclive data/stft.dill data/cross_validation_split_4.json data/model_cv_4.pkl data/output_test_cv_4.csv
    deps:
    - src/model_runner.py
    - src/models/__IModel.py
    - src/models/CNN.py
    - src/models/utils/DataLoaderNDArray.py
    - src/models/utils/DataSetTabular.py
    - data/stft.dill
    - data/cross_validation_split_4.json
    params:
    - dvclive
    outs:
    - data/model_cv_4.pkl
    - data/output_test_cv_4.csv

  cross_validation_run_5:
    cmd: python src/model_runner.py dvclive data/stft.dill data/cross_validation_split_5.json data/model_cv_5.pkl data/output_test_cv_5.csv
    deps:
    - src/model_runner.py
    - src/models/__IModel.py
    - src/models/CNN.py
    - src/models/utils/DataLoaderNDArray.py
    - src/models/utils/DataSetTabular.py
    - data/stft.dill
    - data/cross_validation_split_5.json
    params:
    - dvclive
    outs:
    - data/model_cv_5.pkl
    - data/output_test_cv_5.csv

  cross_validation_run_6:
    cmd: python src/model_runner.py dvclive data/stft.dill data/cross_validation_split_6.json data/model_cv_6.pkl data/output_test_cv_6.csv
    deps:
    - src/model_runner.py
    - src/models/__IModel.py
    - src/models/CNN.py
    - src/models/utils/DataLoaderNDArray.py
    - src/models/utils/DataSetTabular.py
    - data/stft.dill
    - data/cross_validation_split_6.json
    params:
    - dvclive
    outs:
    - data/model_cv_6.pkl
    - data/output_test_cv_6.csv

  cross_validation_run_7:
    cmd: python src/model_runner.py dvclive data/stft.dill data/cross_validation_split_7.json data/model_cv_7.pkl data/output_test_cv_7.csv
    deps:
    - src/model_runner.py
    - src/models/__IModel.py
    - src/models/CNN.py
    - src/models/utils/DataLoaderNDArray.py
    - src/models/utils/DataSetTabular.py
    - data/stft.dill
    - data/cross_validation_split_7.json
    params:
    - dvclive
    outs:
    - data/model_cv_7.pkl
    - data/output_test_cv_7.csv

  cross_validation_run_8:
    cmd: python src/model_runner.py dvclive data/stft.dill data/cross_validation_split_8.json data/model_cv_8.pkl data/output_test_cv_8.csv
    deps:
    - src/model_runner.py
    - src/models/__IModel.py
    - src/models/CNN.py
    - src/models/utils/DataLoaderNDArray.py
    - src/models/utils/DataSetTabular.py
    - data/stft.dill
    - data/cross_validation_split_8.json
    params:
    - dvclive
    outs:
    - data/model_cv_8.pkl
    - data/output_test_cv_8.csv

  cross_validation_run_9:
    cmd: python src/model_runner.py dvclive data/stft.dill data/cross_validation_split_9.json data/model_cv_9.pkl data/output_test_cv_9.csv
    deps:
    - src/model_runner.py
    - src/models/__IModel.py
    - src/models/CNN.py
    - src/models/utils/DataLoaderNDArray.py
    - src/models/utils/DataSetTabular.py
    - data/stft.dill
    - data/cross_validation_split_9.json
    params:
    - dvclive
    outs:
    - data/model_cv_9.pkl
    - data/output_test_cv_9.csv

  cross_validation_run_10:
    cmd: python src/model_runner.py dvclive data/stft.dill data/cross_validation_split_10.json data/model_cv_10.pkl data/output_test_cv_10.csv
    deps:
    - src/model_runner.py
    - src/models/__IModel.py
    - src/models/CNN.py
    - src/models/utils/DataLoaderNDArray.py
    - src/models/utils/DataSetTabular.py
    - data/stft.dill
    - data/cross_validation_split_10.json
    params:
    - dvclive
    outs:
    - data/model_cv_10.pkl
    - data/output_test_cv_10.csv

  evaluate_cv:
    cmd: python src/evaluate_cv.py evaluate_cv data/output_test_cv_ evaluation/metrics_cv.png
    deps:
    - src/evaluate_cv.py
    - data/output_test_cv_1.csv
    - data/output_test_cv_2.csv
    - data/output_test_cv_3.csv
    - data/output_test_cv_4.csv
    - data/output_test_cv_5.csv
    - data/output_test_cv_6.csv
    - data/output_test_cv_7.csv
    - data/output_test_cv_8.csv
    - data/output_test_cv_9.csv
    - data/output_test_cv_10.csv
    outs:
    - evaluation/metrics_cv.png