stages:
  pull_data:
    cmd: python src/pull_data.py data/db_pull_calibrated.parquet data/db_pull_uncalibrated.parquet
    deps:
    - src/pull_data.py
    - src/utils/dbconnector.py
    params:
    - database.questdb
    outs:
    - data/db_pull_calibrated.parquet
    - data/db_pull_uncalibrated.parquet
  resample:
    cmd: python src/resample.py data/db_pull_calibrated.parquet 50 linear
    deps:
    - data/db_pull_calibrated.parquet
    - src/resample.py
    outs:
    - data/resample.parquet
  segmentate:
    cmd: python src/segmentate.py data/resample.parquet 5 0
    deps:
    - data/resample.parquet
    - src/segmentate.py
    outs:
    - data/segmentate.dill
  fft:
    cmd: python src/fft.py data/segmentate.dill
    deps:
    - data/segmentate.dill
    - src/fft.py
    outs:
    - data/fft.dill
  filter_bandpass:
    cmd: python src/filter_bandpass.py data/segmentate.dill 0.001 100 3
    deps:
    - data/segmentate.dill
    - src/filter_bandpass.py
    - src/utils/filters.py
    outs:
    - data/bandpass.dill
  filter_lowpass:
    cmd: python src/filter_lowpass.py data/segmentate.dill 100 3
    deps:
    - data/segmentate.dill
    - src/filter_lowpass.py
    - src/utils/filters.py
    outs:
    - data/lowpass.dill
  filter_highpass:
    cmd: python src/filter_highpass.py data/segmentate.dill 0.001 3
    deps:
    - data/segmentate.dill
    - src/filter_highpass.py
    - src/utils/filters.py
    outs:
    - data/highpass.dill
  moving_average:
    cmd: python src/moving_average.py data/resample.parquet data/moving_average.parquet
    deps:
    - data/resample.parquet
    - src/moving_average.py
    params:
    - moving_average.window_len_s
    outs:
    - data/moving_average.parquet
  pca:
    cmd: python src/pca.py data/resample.parquet 6
    deps:
    - data/resample.parquet
    - src/pca.py
    outs:
    - data/pca.parquet
