stages:
  pull_data:
    cmd: python src/pull_data.py data/db_pull.parquet
    deps:
    - config.json
    - src/pull_data.py
    - src/utils/dbconnector.py
    outs:
    - data/db_pull.parquet
  resample:
    cmd: python src/resample.py data/db_pull.parquet 50 linear
    deps:
    - data/db_pull.parquet
    - src/resample.py
    outs:
    - data/resample.parquet
