database:
  questdb:
    table_name: prod
    host: docker.great-squeaker.ts.net
    port: 9000
  metadata_attributes:
  - hash
  - person
  - activity

moving_average:
  window_len_s: 0.5

train_test_split:
  type: person
  test_ratio: 0.2
  seed: 9458
  stratified: True

OneHotEncode:
  Sitzen: 0
  Laufen: 1
  Velofahren: 2
  Rennen: 3
  Stehen: 4
  Treppenlaufen: 5
