database:
  questdb:
    table_name: prod
    host: docker.great-squeaker.ts.net
    port: 9000
  metadata_attributes:
  - hash
  - person
  - activity

moving_average:
  window_len_s: 0.5

train_test_split:
  type: person
  test_ratio: 0.2
  seed: 9458
  stratified: true

filters:
  bandpass:
    lowcut_f_Hz: 0.1
    highcut_f_Hz: 100
    order: 3
  lowpass:
    cutoff_f_Hz: 100
    order: 3
  highpass:
    cutoff_f_Hz: 0.1
    order: 3

aggregate:
- mean
- median
- std

dvclive:
  model: MLP
  seed: 42
  data:
    type: Tabular
    input_size: 72
    output_size: 6
    num_workers: 0
    train_val_split: 0.8
    batch_size: 32
  model_hparams:
    num_epochs: 100
    learning_rate: 0.03
    weight_decay: 0.0005
    momentum: 0.9
