pull_data_calibrated:
  database:
    questdb:
      table_name: prod
      host: docker.great-squeaker.ts.net
      port: 9000
  get_calibrated: true

resample_50Hz:
  resample_frequency_hz: 50
  interpolation_method: linear

segmentate_5s:
  window_len_s: 5
  overlap_percent: 0

filter_bandpass_ord3_low01_high100:
  filter_type: bandpass
  order: 3
  lowcut_f_Hz: 0.1
  highcut_f_Hz: 100

filter_lowpass_ord3_cut100:
  filter_type: lowpass
  order: 3
  cutoff_f_Hz: 100

filter_highpass_ord3_cut01:
  filter_type: highpass
  order: 3
  cutoff_f_Hz: 0.1

moving_average_01s:
  window_len_s: 0.1

train_test_split_ratio02:
  type: measurement
  test_ratio: 0.2
  seed: 9458
  stratified: true

correlations_pearson:
  correlation_method: pearson

aggregate_mean_median_std:
- mean
- median
- std

transform_min_max:
  transformation: min-max
  transformation_params:
    feature_range_min: 0
    feature_range_max: 1

transform_standardize:
  transformation: standardize

transform_pca:
  transformation: pca
  transformation_params:
    n_components: 6

# AdaBoostStumpClassifier model
dvclive:
  model: AdaBoostStumpClassifier
  seed: 42
  data:
    type: Sklearn_Segments
    params:
      columns: "numeric"
  model_hparams:
    learning_rate: 0.5
    n_estimators: 200
    random_state: 42